version: '3'

services:

  # backend:
  #   build: ./backend
  #   command: python server.py
  #   environment:
  #     NODE_ENV: development
  #   networks:
  #     - backend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./backend:/usr/src/app:ro
  #
  # frontend:
  #   build: ./frontend
  #   command: npm start
  #   environment:
  #     NODE_ENV: development
  #   networks:
  #     - backend
  #   ports:
  #     - '3001:3001'
  #     - '35729:35729'
  #   volumes:
  #     - ./backend:/usr/src/backend:rw
  #     - ./frontend:/usr/src/app:rw
  #     - /usr/src/app/node_modules

  hub:
    image: selenium/hub
    networks:
      - backend
    ports:
      - "4444:4444"

  chrome_node:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - backend
    depends_on:
      - hub
    ports:
      - 5900:5900

  firefox_node:
    image: selenium/node-firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - backend
    depends_on:
      - hub
    ports:
      - 5901:5901

  owasp_zap:
    image: owasp/zap2docker-stable
    networks:
      - backend
    ports:
      - "8081:8081"
    command: zap.sh -daemon -port 8081 -host 0.0.0.0 -config api.key=0123456789 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config scanner.strength=INSANE

  lighthouse:
    image: kmturley/lighthouse-ci
    networks:
      - backend
    ports:
      - "8085:8085"

  verify_functionality_:
    image: python:3.6.4-jessie
    networks:
      - backend
    depends_on:
      - hub



networks:
  backend:
    driver: bridge
