version: "3"

services:

  selenium_hub:
    image: selenium/hub:3.9.1-actinium
    # depends_on:
    #   - deploy
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - qa_network
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 10
      GRID_TIMEOUT: 180000
      GRID_BROWSER_TIMEOUT: 180000
      SHM_SIZE: 512MB
      GRID_NEW_SESSION_WAIT_TIMEOUT: 180000

  selenium_firefox_node:
    image: selenium/node-firefox:3.9.1-actinium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      FIREFOX_VERSION: 58.0.1
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub

  selenium_last_firefox_node:
    image: selenium/node-firefox:3.9.1-actinium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      SE_OPTS: -browser browserName=firefox,version=57.0.4,maxInstances=5,maxSessions=5
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub

  selenium_chrome_node:
    image: selenium/node-chrome:3.9.1-actinium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      # CHROME_VERSION: 64
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub

  selenium_last_chrome_node:
    image: selenium/node-chrome:3.9.1-actinium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      SE_OPTS: -browser browserName=chrome,version=63.0.3239,maxInstances=5,maxSessions=5
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    networks:
      - qa_network
    links:
      - selenium_hub:hub


  owasp_zap_server:
    image: owasp/zap2docker-stable
    networks:
      - qa_network
    ports:
      - "8081:8081"
    command: zap.sh -daemon -port 8081 -host 0.0.0.0 -config api.key=0123456789 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config scanner.strength=INSANE


  lighthouse_server:
    image: kmturley/lighthouse-ci
    networks:
      - qa_network
    ports:
      - "8085:8085"


  functional_current_chrome:
    build:
      context: ./qa
    depends_on:
      - selenium_chrome_node
    environment:
      BASE_URL: 'https://google.com'
      DRIVER: 'headless_chrome'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
    volumes:
      - ./qa/utilities/allure/allure_result_folder:/usr/tmp/qa/utilities/allure/allure_result_folder:consistent
    networks:
      - qa_network
    command:
      bash -c ". /usr/tmp/qa/wait-for-node.sh chrome:64.0.3282.140 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  qa/utilities/allure/allure_result_folder ./qa/functional/features -i google"

  functional_last_chrome:
    build:
      context: ./qa
    depends_on:
      - selenium_last_chrome_node
    environment:
      BASE_URL: 'https://google.com'
      DRIVER: 'last_headless_chrome'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
    volumes:
      - ./qa/utilities/allure/allure_result_folder:/usr/tmp/qa/utilities/allure/allure_result_folder:consistent
    networks:
      - qa_network
    command:
      bash -c ". /usr/tmp/qa/wait-for-node.sh chrome:63.0.3239 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  qa/utilities/allure/allure_result_folder ./qa/functional/features -i google"


  functional_current_firefox:
    build:
      context: ./qa
    depends_on:
      - selenium_firefox_node
    environment:
      BASE_URL: 'https://google.com'
      DRIVER: 'remote_firefox'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
    volumes:
      - ./qa/utilities/allure/allure_result_folder:/usr/tmp/qa/utilities/allure/allure_result_folder:consistent
    networks:
      - qa_network
    command:
      bash -c ". /usr/tmp/qa/wait-for-node.sh firefox:58.0.1 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  qa/utilities/allure/allure_result_folder ./qa/functional/features -i google"

  functional_last_firefox:
    build:
      context: ./qa
    depends_on:
      - selenium_last_firefox_node
    environment:
      BASE_URL: 'https://google.com'
      DRIVER: 'last_remote_firefox'
      SELENIUM: 'http://selenium_hub:4444/wd/hub'
    volumes:
      - ./qa/utilities/allure/allure_result_folder:/usr/tmp/qa/utilities/allure/allure_result_folder:consistent
    networks:
      - qa_network
    command:
      bash -c ". /usr/tmp/qa/wait-for-node.sh firefox:57.0.4 --selenium_hub=selenium_hub -- behave -f allure_behave.formatter:AllureFormatter -o  qa/utilities/allure/allure_result_folder ./qa/functional/features -i google"

  performance_tests:
    build:
      context: ./qa
    # depends_on:
      # - build
    environment:
      BASE_URL: 'https://google.com'
    volumes:
      - ./qa/utilities/allure/allure_result_folder:/usr/tmp/qa/utilities/allure/allure_result_folder:consistent
    networks:
      - qa_network
    command: bash -c "python3 qa/performance/allure_runner.py"

  visual_current_chrome:
    build:
      context: ./qa
      # depends_on:
      # - build
    environment:
      BASE_URL: 'https://google.com'
    networks:
      - qa_network
    command: bash -c ". /usr/tmp/qa/wait-for-node.sh chrome:64.0.3282.140 --selenium_hub=selenium_hub -- galen test qa/visual/tests/ --config qa/visual/docker_configs/current_remote_chrome.config"

  visual_last_chrome:
    build:
      context: ./qa
    # depends_on:
      # - build
    environment:
      BASE_URL: 'https://google.com'
    networks:
      - qa_network
    command: bash -c ". /usr/tmp/qa/wait-for-node.sh chrome:63.0.3239 --selenium_hub=selenium_hub -- galen test qa/visual/tests/ --config qa/visual/docker_configs/last_remote_chrome.config"

  visual_current_firefox:
    build:
      context: ./qa
    # depends_on:
      # - build
    environment:
      BASE_URL: 'https://google.com'
    networks:
      - qa_network
    command: bash -c ". /usr/tmp/qa/wait-for-node.sh firefox:58.0.1 --selenium_hub=selenium_hub -- galen test qa/visual/tests/ --config qa/visual/docker_configs/current_remote_firefox.config"

  visual_last_firefox:
    build:
      context: ./qa
    # depends_on:
      # - build
    environment:
      BASE_URL: 'https://google.com'
    networks:
      - qa_network
    command: bash -c ". /usr/tmp/qa/wait-for-node.sh firefox:57.0.4 --selenium_hub=selenium_hub -- galen test qa/visual/tests/ --config qa/visual/docker_configs/last_remote_firefox.config"


networks:
  qa_network:
    driver: bridge

# volumes:
#   reports-volume
